/**
 * Company brand themes for tailored resume routes.
 * Colors / domains sourced from public brand references (Brandfetch, brand guidelines, press kits).
 * Only companies with clear public brand identity are listed.
 */
window.COMPANIES = {
  wolt: {
    name: "Wolt",
    slug: "wolt",
    domain: "wolt.com",
    industry: "Food delivery & local commerce",
    primary: "#00C2E8",
    primaryDark: "#0090B0",
    secondary: "#141414",
    accent: "#FFFFFF",
    bg: "#F4FBFD",
    surface: "#FFFFFF",
    text: "#141414",
    muted: "#4B5563",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Wolt — product engineering at delivery scale",
    pitch:
      "Experience shipping high-DAU consumer surfaces, performance-sensitive UI, and real-time product features relevant to marketplace delivery platforms.",
    layout: "magazine",
    threeMode: "orbs",
    particlesMode: "constellation",
    fxIntensity: "heavy"},
  bolt: {
    name: "Bolt",
    slug: "bolt",
    domain: "bolt.eu",
    industry: "Mobility & delivery",
    primary: "#34D186",
    primaryDark: "#1FAF68",
    secondary: "#121212",
    accent: "#FFFFFF",
    bg: "#F3FBF7",
    surface: "#FFFFFF",
    text: "#121212",
    muted: "#4B5563",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Bolt — high-scale mobility product engineering",
    pitch:
      "Background in large-scale web apps, mobile (React Native), and ops-aware frontend leadership for multi-market consumer products.",
    layout: "split-diagonal",
    threeMode: "torus",
    particlesMode: "energy",
    fxIntensity: "heavy"},
  zalando: {
    name: "Zalando",
    slug: "zalando",
    domain: "zalando.com",
    industry: "Fashion e-commerce",
    primary: "#FF6900",
    primaryDark: "#E05A00",
    secondary: "#1A1A1A",
    accent: "#FFFFFF",
    bg: "#FFF8F3",
    surface: "#FFFFFF",
    text: "#1A1A1A",
    muted: "#5C5C5C",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Zalando — commerce UI & platform craft",
    pitch:
      "Strong commerce & dashboard experience (billing, analytics, merchant tools) plus performance and accessibility ownership at scale.",
    layout: "bold-editorial",
    threeMode: "crystal",
    particlesMode: "embers",
    fxIntensity: "heavy"},
  "delivery-hero": {
    name: "Delivery Hero",
    slug: "delivery-hero",
    domain: "deliveryhero.com",
    industry: "Delivery platforms",
    primary: "#D70F64",
    primaryDark: "#B00C52",
    secondary: "#1A1A1A",
    accent: "#FFFFFF",
    bg: "#FFF5F9",
    surface: "#FFFFFF",
    text: "#1A1A1A",
    muted: "#5C5C5C",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Delivery Hero — multi-brand delivery engineering",
    pitch:
      "Built F&B ordering experiences at 50k+ DAU and revenue-critical merchant tooling — aligned with delivery platform product challenges.",
    layout: "cards-float",
    threeMode: "network",
    particlesMode: "burst",
    fxIntensity: "heavy"},
  aviv: {
    name: "Aviv Group",
    slug: "aviv",
    domain: "aviv-group.com",
    industry: "Real estate tech",
    primary: "#00A0E3",
    primaryDark: "#0080B8",
    secondary: "#0B1D2A",
    accent: "#FFFFFF",
    bg: "#F3FAFD",
    surface: "#FFFFFF",
    text: "#0B1D2A",
    muted: "#4B5C6B",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Aviv Group — product UI for property marketplaces",
    pitch:
      "Experience leading product UI, CMS-driven content surfaces, and reliable high-traffic web platforms for consumer marketplaces.",
    layout: "sidebar",
    threeMode: "boxes",
    particlesMode: "soft-mesh",
    fxIntensity: "heavy"},
  flink: {
    name: "Flink",
    slug: "flink",
    domain: "goflink.com",
    industry: "Quick commerce",
    primary: "#00E599",
    primaryDark: "#00B87A",
    secondary: "#0A0A0A",
    accent: "#0A0A0A",
    bg: "#F2FCF8",
    surface: "#FFFFFF",
    text: "#0A0A0A",
    muted: "#4B5563",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Flink — speed, reliability & consumer UX",
    pitch:
      "Shipped high-frequency commerce and operations tooling with real-time features, mobile apps, and performance focus.",
    layout: "gradient-wave",
    threeMode: "orbs",
    particlesMode: "rain",
    fxIntensity: "heavy"},
  home24: {
    name: "Home24",
    slug: "home24",
    domain: "home24.com",
    industry: "Home & living e-commerce",
    primary: "#FF5A00",
    primaryDark: "#D94B00",
    secondary: "#1A1A1A",
    accent: "#FFFFFF",
    bg: "#FFF7F2",
    surface: "#FFFFFF",
    text: "#1A1A1A",
    muted: "#5C5C5C",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Home24 — e-commerce product engineering",
    pitch:
      "Commerce-facing UI, analytics dashboards, and full product lifecycle delivery with React/TypeScript and Node.js.",
    layout: "polaroid",
    threeMode: "stars",
    particlesMode: "dust",
    fxIntensity: "heavy"},
  otto: {
    name: "OTTO",
    slug: "otto",
    domain: "otto.de",
    industry: "E-commerce",
    primary: "#E30613",
    primaryDark: "#B8050F",
    secondary: "#1A1A1A",
    accent: "#FFFFFF",
    bg: "#FFF5F5",
    surface: "#FFFFFF",
    text: "#1A1A1A",
    muted: "#5C5C5C",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for OTTO — large-scale retail digital experiences",
    pitch:
      "Senior ownership of performant, accessible storefronts and internal tools — leadership + hands-on React/Next.js delivery.",
    layout: "ribbon",
    threeMode: "torus",
    particlesMode: "constellation",
    fxIntensity: "heavy"},
  xxxlutz: {
    name: "XXXLutz",
    slug: "xxxlutz",
    domain: "xxxlutz.de",
    industry: "Furniture retail",
    primary: "#E30613",
    primaryDark: "#B8050F",
    secondary: "#1A1A1A",
    accent: "#FFFFFF",
    bg: "#FFF5F5",
    surface: "#FFFFFF",
    text: "#1A1A1A",
    muted: "#5C5C5C",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for XXXLutz — retail web & conversion UX",
    pitch:
      "Experience building conversion-oriented web products, admin tooling, and team delivery for multi-channel retail contexts.",
    layout: "compact-board",
    threeMode: "boxes",
    particlesMode: "grid",
    fxIntensity: "heavy"},
  amazon: {
    name: "Amazon",
    slug: "amazon",
    domain: "amazon.com",
    industry: "E-commerce & cloud",
    primary: "#FF9900",
    primaryDark: "#E88B00",
    secondary: "#232F3E",
    accent: "#232F3E",
    bg: "#FFFBF5",
    surface: "#FFFFFF",
    text: "#0F1111",
    muted: "#565959",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Amazon — customer-obsessed product engineering",
    pitch:
      "Track record on high-traffic customer journeys, measurable impact, operational excellence (monitoring, gateway, security), and mentoring engineers.",
    layout: "classic",
    threeMode: "network",
    particlesMode: "orbit",
    fxIntensity: "heavy"},
  langdock: {
    name: "Langdock",
    slug: "langdock",
    domain: "langdock.com",
    industry: "Enterprise AI platform",
    primary: "#5B5FFF",
    primaryDark: "#4548D9",
    secondary: "#0B0B12",
    accent: "#FFFFFF",
    bg: "#F6F6FF",
    surface: "#FFFFFF",
    text: "#0B0B12",
    muted: "#4B5563",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Langdock — product UI for AI adoption platforms",
    pitch:
      "Modern stack (React, Next.js, TypeScript, Node) plus CMS/content systems and production hardening — suited to AI product surfaces and admin experiences.",
    layout: "neon-cyber",
    threeMode: "crystal",
    particlesMode: "neon",
    fxIntensity: "heavy"},
  hometogo: {
    name: "HomeToGo",
    slug: "hometogo",
    domain: "hometogo.com",
    industry: "Travel marketplace",
    primary: "#00B67A",
    primaryDark: "#009563",
    secondary: "#0D1B2A",
    accent: "#FFFFFF",
    bg: "#F2FBF7",
    surface: "#FFFFFF",
    text: "#0D1B2A",
    muted: "#4B5C6B",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for HomeToGo — marketplace UX at scale",
    pitch:
      "Marketplace & multi-product UI experience with performance, SEO/analytics sensibility, and cross-functional delivery leadership.",
    layout: "soft-mesh",
    threeMode: "orbs",
    particlesMode: "bubbles",
    fxIntensity: "heavy"},
  "trade-republic": {
    name: "Trade Republic",
    slug: "trade-republic",
    domain: "traderepublic.com",
    industry: "Fintech / brokerage",
    primary: "#00D26A",
    primaryDark: "#00A854",
    secondary: "#0A0A0A",
    accent: "#0A0A0A",
    bg: "#F2FBF6",
    surface: "#FFFFFF",
    text: "#0A0A0A",
    muted: "#4B5563",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Trade Republic — regulated fintech product engineering",
    pitch:
      "Currently owns Internet Banking UI under RBI compliance (~1M users/day) — strong fit for regulated financial product quality, security, and reliability.",
    layout: "noir",
    threeMode: "stars",
    particlesMode: "matrix",
    fxIntensity: "heavy"},
  contentful: {
    name: "Contentful",
    slug: "contentful",
    domain: "contentful.com",
    industry: "Content platform / CMS",
    primary: "#1778EB",
    primaryDark: "#125FBC",
    secondary: "#0C0C0C",
    accent: "#FFFFFF",
    bg: "#F4F8FE",
    surface: "#FFFFFF",
    text: "#0C0C0C",
    muted: "#4B5563",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Contentful — content-driven product engineering",
    pitch:
      "Hands-on Next.js SSR + Prismic CMS for dynamic UI composition; deep React/TypeScript product experience for content platforms and developer-facing tools.",
    layout: "stack-timeline",
    threeMode: "network",
    particlesMode: "links",
    fxIntensity: "heavy"},
  revolut: {
    name: "Revolut",
    slug: "revolut",
    domain: "revolut.com",
    industry: "Fintech / neobank",
    primary: "#0666EB",
    primaryDark: "#0450BA",
    secondary: "#191C1F",
    accent: "#FFFFFF",
    bg: "#F3F7FE",
    surface: "#FFFFFF",
    text: "#191C1F",
    muted: "#4B5563",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Revolut — fintech product quality at scale",
    pitch:
      "Banking-scale frontend leadership, security (CAPTCHA, gateway policies), observability, and performance — built for high-trust financial products.",
    layout: "dark-immersive",
    threeMode: "torus",
    particlesMode: "fintech",
    fxIntensity: "heavy"},
  taxfix: {
    name: "Taxfix",
    slug: "taxfix",
    domain: "taxfix.com",
    industry: "Tax & finance software",
    primary: "#00D37F",
    primaryDark: "#00A864",
    secondary: "#001F17",
    accent: "#001F17",
    bg: "#F2FCF7",
    surface: "#FFFFFF",
    text: "#001F17",
    muted: "#3D5C52",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Taxfix — trustworthy finance product UX",
    pitch:
      "Experience in regulated financial UX, clear information architecture, accessibility, and production reliability for customer-critical flows.",
    layout: "aurora",
    threeMode: "crystal",
    particlesMode: "soft-mesh",
    fxIntensity: "heavy"},
  wise: {
    name: "Wise",
    slug: "wise",
    domain: "wise.com",
    industry: "Fintech / cross-border payments",
    primary: "#9FE870",
    primaryDark: "#6FCF3F",
    secondary: "#163300",
    accent: "#163300",
    bg: "#F7FCF2",
    surface: "#FFFFFF",
    text: "#163300",
    muted: "#3D4F2F",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for Wise — clear, global product engineering",
    pitch:
      "High-traffic financial journeys, performance & security hardening, and team leadership — aligned with transparent, customer-first fintech products.",
    layout: "isometric",
    threeMode: "boxes",
    particlesMode: "bounce",
    fxIntensity: "heavy"},
  n8n: {
    name: "n8n",
    slug: "n8n",
    domain: "n8n.io",
    industry: "Workflow automation",
    primary: "#EA4B71",
    primaryDark: "#C93A5C",
    secondary: "#040506",
    accent: "#FFFFFF",
    bg: "#FFF5F8",
    surface: "#FFFFFF",
    text: "#040506",
    muted: "#4B5563",
    font: '"Inter", system-ui, sans-serif',
    headingFont: '"Inter", system-ui, sans-serif',
    tagline: "Tailored for n8n — product engineering for builder tools",
    pitch:
      "Full-stack product craft (React/TS/Node), real-time systems, and developer-adjacent tooling experience for complex workflow products.",
    layout: "terminal",
    threeMode: "network",
    particlesMode: "nodes",
    fxIntensity: "heavy"},
};

window.COMPANY_LIST = Object.keys(window.COMPANIES).map(function (k) {
  return window.COMPANIES[k];
});
